---
driver:
  name: dokken
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
- name: debian
  driver_config:
    image: debian:8.9
    intermediate_instructions:
      - RUN /usr/bin/apt-get update &&
          /usr/bin/apt-get install apt-transport-https net-tools curl openssl --yes --no-install-recommends

verifier:
  name: inspec
  root_path: '/opt/verifier'
  sudo: false

suites:
  - name: default
    run_list:
      - recipe[dataduct::default]
  - name: config
    run_list:
      - recipe[dataduct-test::config]
