sudo: required
dist: trusty
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

install: echo "skip bundle install"

services: docker

env:
  matrix:
    - INSTANCE=default-debian
    - INSTANCE=config-debian

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version
  - chef gem install kitchen-dokken

script:
  - KITCHEN_LOCAL_YAML=.kitchen.yml kitchen verify ${INSTANCE}

after_script:
  - docker images
  - docker ps -a
  - cat .kitchen/logs/kitchen.log

matrix:
  include:
    - script: "cookstyle"
      env: COOKSTYLE=1
    - script: "foodcritic . --exclude spec -f any -P --tags ~FC122"
      env: FOODCRITIC=1
    - script: "rspec"
      env: CHEFSPEC=1
